### ISSUE TITLE
新手请教啊

### ISSUE THREAD

**Issue by excxapp** [kailuo99/toutiao#1]
我下载了你的源码，安装之后提示一些错误：
# import "RCTBorderStyle.h"

/Applications/XAMPP/xamppfiles/htdocs/toutiao/node_modules/react-native/React/Base/RCTConvert.h:15:9: 'RCTBorderStyle.h' file not found

都是这些东西，都是发现不了文件，请问是什么原因，您知道吗？

**Comment by kailuo99** [comment]
你在项目根目录执行：npm install 试试

**Comment by j306796405** [comment]
我也是这个问题  npm install 过了。

**Comment by ghost** [comment]
一样是这个错误

**Comment by huangjian80s** [comment]
我也是这个问题，麻烦博主帮助一下啊

**Comment by kailuo99** [comment]
这个问题是因为 node_modules/react-native/React/Views/目录下没有RCTBorderStyle.h文件造成的。node_modules下面的东西都是通过npm安装的。删除node_modules目录，重新执行npm install 应该就能解决了

**Comment by TuyaRonbin** [comment]
在项目目录下执行命令sudo npm install

**Comment by kkzzzzzz** [comment]
@xuchengcheng The way he mentioned can solve the problem
