### ISSUE TITLE
不能用啊

### ISSUE THREAD

**Issue by yidashi** [kailuo99/toutiao#2]
RCTBorderStyle.h not found

**Comment by TheWalkingDead1024** [comment]
我也遇到了这个问题

**Comment by zsf513** [comment]
问题同上，没有RCTBorderStyle.h

**Comment by LLbgithub** [comment]
不能使用，问题同上

**Comment by kailuo99** [comment]
这个问题是因为 node_modules/react-native/React/Views/目录下没有RCTBorderStyle.h文件造成的。node_modules下面的东西都是通过npm安装的。删除node_modules目录，重新执行npm install 应该就能解决了
